ktor:
  application:
    modules:
      - com.avcoding.scribblesphere.ApplicationKt.module
  deployment:
    port: 8080
    host: 192.168.1.41
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
